cafe/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('', views.company, name='infofabout'),
]

cafe/cafe/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'), name='homepage'),
    path('about/', include('about.urls'), name='about'),
    path('contacts/', include('contacts.urls'), name='about'),
    path('menu/', include('menu.urls'), name='menu'),
]

cafe/contacts/urls.py
from django.urls import path

from . import views


app_name = 'contacts'

urlpatterns = [
    path('', views.contacts, name='infofcontacts'),
]

cafe/homepage/urls.py
from django.urls import path

from . import views


app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

cafe/menu/urls.py
from django.urls import path

from . import views


app_name = 'menu'

urlpatterns = [
    path('pizza/', views.pizza, name='infofpizza'),
    path('burger/', views.burger, name='infofburger'),
    path('drink/', views.drink, name='infofdrink'),
]

cafe/about/models.py
from django.db import models

# Create your models here.

cafe/contacts/models.py
from django.db import models

# Create your models here.

cafe/homepage/models.py
from django.db import models

# Create your models here.

cafe/menu/models.py
from django.db import models

# Create your models here.

cafe/about/views.py
from django.shortcuts import render


def company(request):
    return render(request, "about/about.html")

cafe/contacts/views.py
from django.shortcuts import render


def contacts(request):
    return render(request, "contacts/contacts.html")

cafe/homepage/views.py
from django.shortcuts import render


def index(request):
    return render(request, "homepage/index.html")

cafe/menu/views.py
from django.shortcuts import render


def pizza(request):
    return render(request, "menu/pizza.html")


def burger(request):
    return render(request, "menu/burger.html")


def drink(request):
    return render(request, "menu/drink.html")

cafe/templates/about/about.html
{% extends "base.html" %}
{% load static %}
{% block style %} 
  <link rel="stylesheet" href={% static "css/styleofCompany.css" %}>
{% endblock %}
{% block content %}
    <p class="Companyheader">О нас</p>
    <p class="Textcompany">Если вы привыкли двигаться в ускоренном темпе, то сама идея быстрой еды для вас не будет в новинку. Для тех, кто желает скорее перекусить в перерыве между делами, кафе быстрого питания Гараж предлагает ряд простых, но питательных блюд по умеренным ценам. Еда готовится таким образом, чтобы ее можно было взять с собой.
                           Всех гостей ждут по адресу: Республика Северная Осетия — Алания, улица Морских Пехотинцев, 8. 
                           Для гостей заведение работает Пн-вс: 10:00 - 23:00.
    </p>
    <div class="Statistic">
      <p class="NameofStatistic">Статистика</p>
      <img class="Statisticimg" src={% static "img/Statistic.png" %} width="100%" height="100%">
    </div>
    <p class="HeaderCoor">Наши Координаты</p>
    <center>    
      <script class="Map" type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Adb0f0b29f7462e5bae0e9063f22dfc5fe228fca051e5bf361a3542e0f217ec6c&amp;width=70%&amp;height=100%&amp;lang=ru_RU&amp;scroll=true"></script>
    </center>
{% endblock %}

cafe/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  {% block style %}{% endblock %}
  <title>
    Гараж
  </title>
</head>
<body> 
  {% include "includes/header.html" %}
  <main>
    {% block content %}{% endblock %}
  </main>
  {% include "includes/footer.html" %}
</body>
</html>

cafe/templates/contacts/contacts.html
{% extends "base.html" %}
{% load static %}
{% block style %}
  <link rel="stylesheet" href={% static 'css/styleofContacts.css' %}>
{% endblock %}
{% block content %}
<div class="Contacts"><p>Адрес<br>
    ул. Морских Пехотинцев, 8, Владикавказ<br>
    Контакты<br>
    +7 (937) 977-17-77<br>
    Время работы<br>
    Открыто с 10:00 до 23:00</p></div>
{% endblock %}

cafe/templates/homepage/index.html
{% extends "base.html" %}
{% load static %}
{% block style %}
  <link rel="stylesheet" href="{% static 'css/styleofGlavnaya.css' %}">
{% endblock %}
{% block content %}
  <div class="row">
    <p class="textglav">Кафе быстрого питания "Гараж"  приглашает вас окунуться в атмосферу любимых вкусов.
    Здесь можно сытно перекусить как одному, так и в компании друзей или семьи.
    Еда готовится таким образом, чтобы ее можно было взять с собой.</p>
  </div>
{% endblock %}

cafe/templates/includes/footer.html
{% load static %}
<footer>
    <table>
      <tr>
        <td><p class="NameFootlink">Главная</p></td>
        <td><p class="NameFootlink">Меню</p></td>
        <td><p class="NameFootlink">О компании</p></td>
        <td><p class="NameFootlink">Контакты</p></td>
        <td><p class="SocialFootlink">Наша социальная сеть</p></td>
      </tr>
      <tr>
        <td><a class="Footlink" href="index.html">Главная страница</a></td>
        <td>
          <a class="Footlink" href="Пицца.html">Пицца</a>
          <br>
          <a class="Footlink" href="Бургеры.html">Бургеры</a>
          <br>
          <a class="Footlink" href="Напитки.html">Напитки</a>
        </td>
        <td><a class="Footlink" href="Company.html">Информация о компании</a></td>
        <td><a class="Footlink" href="Contacts.html">Контакты и обратная связь</a></td>
        <td><a class="IconFootlink" href="https://vk.com/fastfood.garage"><img src="{% static 'img/icons8-вконтакте-48.png' %}"></a></td>
      </tr>
    </table>
</footer>

cafe/templates/includes/header.html
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a class="navbar-brand" href="{% url 'homepage:index' %}">Главная</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            Меню
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'menu:infofpizza' %}">Пиццы</a>
            <a class="dropdown-item" href="{% url 'menu:infofburger' %}">Бургеры</a>
            <a class="dropdown-item" href="{% url 'menu:infofdrink' %}">Напитки</a>
          </div>
        </li>   
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about:infofabout' %}">О компании</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contacts:infofcontacts' %}">Контакты</a>
        </li>
      </ul>
    </div>  
</nav>

cafe/templates/menu/burger.html
{% extends "base.html" %}
{% load static %}
{% block style %}
  <link rel="stylesheet" href={% static "css/styleofBurgers.css" %}>
{% endblock %}
{% block content %}
  <div class="Burgers">
    <p class="Header">Меню бургеров</p>
    <table class="TableofBurger">
      <tr class="Burger">
        <td class="Colomn">
          <img class="Art" src="{% static 'img/The-Frito-Pie-Burger.jpg' %}" height="100%" width="95%">
          <p class="NameofBurger">Бургер "The-Frito-Pie-Burger" - 370p</p>
        </td>
        <td class="Colomn">
          <p class="Structure">Говядина, Булочки из белого хлеба, Перец Холопеньо, Измельченный белый лук, Измельченный сыр Чеддер, Перец Чили</p>
        </td>
      </tr>
      <tr class="Burger">
        <td class="Colomn">
          <img class="Art" src="{% static 'img/Eggs-Benedict-Burger.jpg' %}" height="100%" width="95%">
          <p class="NameofBurger">Пицца "Eggs-Benedict-Burger" - 370p</p>
        </td>
        <td class="Colomn">
          <p class="Structure">Говядина, Перец, Жареное Яйцо, Бекон, Булочки из белого хлеба, Лимон</p>
        </td>
      </tr>
      <tr class="Burger">
        <td class="Colomn">
          <img class="Art" src="{% static 'img/Spaghetti-Burger.jpg' %}" height="100%" width="95%">
          <p class="NameofBurger">Пицца "Spaghetti-Burger" - 370p</p>
        </td>
        <td class="Colomn">
          <p class="Structure">Булочки из белого хлеба, Сливочное масло, Чесночная пудра или соус, Говядина, Спагетти, Соус и зелень</p>
        </td>
      </tr>
    </table>
  </div>
{% endblock %}

cafe/templates/menu/drink.html
{% extends "base.html" %}
{% load static %}
{% block style %}
  <link rel="stylesheet" href={% static "css/styleofDrinks.css" %}>
{% endblock %}
{% block content %}
  <div class="Drinks">
    <p class="Header">Напитки</p>
    <img class="Art" src="{% static 'img/Лимонад.png' %}" height="100%" width="25%">
    <p class="NameofDrink">Лимонад - 70р</p>
    <img class="Art" src="{% static 'img/Чай.png' %}" height="100%" width="55%">
    <p class="NameofDrink">Чай - 90р</p>
    <img class="Art" src="{% static 'img/Махито.png' %}" height="100%" width="55%">
    <p class="NameofDrink">Махито - 170р</p>
    <img class="Art" src="{% static 'img/Сок.png' %}" height="100%" width="25%">
    <p class="NameofDrink">Апельсиновый сок - 95р</p>
    <img class="Art" src="{% static 'img/Пиво.png' %}" height="100%" width="55%">
    <p class="NameofDrink">Пиво - 75р</p>
  </div>
{% endblock %}

cafe/templates/menu/pizza.html
{% extends "base.html" %}
{% load static %}
{% block style %}
  <link rel="stylesheet" href={% static "css/styleofPizza.css" %}>
{% endblock %}
{% block content %}
<div class="Pizza">
    <p class="Header">Меню пицц</p>
    <table class="TableofPizza">
      <tr class="Pizza">
        <td class="Colomn">
          <img class="Art" src="{% static 'img/Баварская.png' %}" height="100%" width="95%">
          <p class="NameofPizza">Пицца "Баварская" - 370p</p>
        </td>
        <td class="Colomn">
          <p class="Structure">Мясо, Субпродукты, Ветчина, Молочные продукты, Сыр, Тесто, Дрожжевое тесто, Колбаса</p>
        </td>
      </tr>
      <tr class="Pizza">
        <td class="Colomn">
          <img class="Art" src="{% static 'img/Барбекю.png' %}" height="100%" width="95%">
          <p class="NameofPizza">Пицца "Барбекю" - 320р</p>
        </td>
        <td class="Colomn">
          <p class="Structure">Овощи, Птица, Курица, Лук, Тесто</p>
        </td>
      </tr>
      <tr class="Pizza">
        <td class="Colomn">
          <img class="Art" src="{% static 'img/Болоньезе.png' %}" height="100%" width="95%">
          <p class="NameofPizza">Пицца "Болоньезе" - 350р</p>
        </td>
        <td class="Colomn">
          <p class="Structure">Мясо, Тесто</p>
        </td>
      </tr>
      <tr class="Pizza">
        <td class="Colomn">
          <img class="Art" src="{% static 'img/Греческая.png' %}" height="100%" width="95%">
          <p class="NameofPizza">Пицца "Греческая" - 340р</p>
        </td>
        <td class="Colomn">
          <p class="Structure">Пшеничные лепешки, Оливковое масло, Моцарелла, Помидоры (томат), Лук репчатый, Оливки без косточки, Фета, Огурец</p>
        </td>
      </tr>
      <tr class="Pizza">
        <td class="Colomn">
          <img class="Art" src="{% static 'img/Деревенская.png' %}">
          <p class="NameofPizza">Пицца "Деревенская" - 335р</p>
        </td>
        <td class="Colomn">
          <p class="Structure">Молочные продукты, Творог, Тесто, Мука</p>
        </td>
      </tr>
      <tr class="Pizza">
        <td class="Colomn">
          <img class="Art" src="{% static 'img/Диабло.png' %}" height="100%" width="95%">
          <p class="NameofPizza">Пицца "Диабло" - 390р</p>
        </td>
        <td class="Colomn">
          <p class="Structure">Мясо, Субпродукты, Молочные продукты, Тесто, Колбаса</p>
        </td>
      </tr>
    </table>
  </div>
{% endblock %}